# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-09-01 17:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('serviceName', models.CharField(max_length=150)),
                ('subServiceName', models.CharField(max_length=150)),
                ('paymentType', models.BooleanField(default=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('papers', models.CharField(max_length=400)),
                ('actions', models.CharField(max_length=400)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
            ],
        ),
        migrations.CreateModel(
            name='SubServiceParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subServiceName', models.CharField(max_length=150)),
                ('paramName', models.CharField(max_length=150)),
                ('isRequired', models.BooleanField(default=True)),
                ('paramType', models.CharField(max_length=150)),
                ('conditions', models.CharField(max_length=300)),
                ('subService', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.SubService')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.Service'),
        ),
        migrations.AddField(
            model_name='order',
            name='subService',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.SubService'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
