# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-09-08 05:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import services.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Geha',
            fields=[
                ('geha_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('geha_name', models.CharField(max_length=50)),
                ('geha_icon', models.ImageField(upload_to=services.models.upload_Geha_Image)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('off_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('off_name', models.CharField(max_length=150)),
                ('off_icon', models.ImageField(upload_to=services.models.upload_Office_Image)),
                ('geha_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Geha')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ord_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ord_date', models.DateField(auto_now=True)),
                ('ord_payment', models.CharField(choices=[('cash on delivery', 'cash on delivery'), ('visa card', 'visa card')], default='cash on delivery', max_length=20)),
                ('status', models.CharField(choices=[('recived', 'recived'), ('paid', 'paid'), ('processing', 'processing'), ('send to delivary', 'sendToDelivary'), ('delivered', 'delivered'), ('canceled', 'canceled'), ('failed', 'failed')], default='recived', max_length=20)),
                ('geha_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Geha')),
                ('off_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.Office')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('srv_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('srv_name', models.CharField(max_length=150)),
                ('canBeOrdered', models.BooleanField(default=False)),
                ('papers', models.TextField(blank=True, default='')),
                ('actions', models.TextField(blank=True, default='')),
                ('geha_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Geha')),
                ('off_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Office')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceParameter',
            fields=[
                ('parm_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parm_name', models.CharField(max_length=50)),
                ('is_rquired', models.BooleanField(default=True)),
                ('parm_icon_name', models.CharField(blank=True, max_length=50)),
                ('param_type', models.CharField(choices=[('Text', 'Text'), ('Number', 'Number'), ('Date', 'Date'), ('City List', 'City List')], default='Text', max_length=40)),
                ('conditions', models.TextField(blank=True)),
                ('srv_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceParameterAnswer',
            fields=[
                ('ans_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parm_name', models.CharField(max_length=50)),
                ('ord_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.ServiceParameter')),
                ('parm_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='srv_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.Service'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
