# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-09-08 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20190908_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivaryplaces',
            name='geha_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Geha'),
        ),
    ]
