# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-07 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20190908_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivaryplaces',
            name='geha_id',
        ),
        migrations.RemoveField(
            model_name='office',
            name='geha_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='geha_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='geha_id',
        ),
        migrations.AddField(
            model_name='delivaryplaces',
            name='off_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Office'),
        ),
        migrations.AddField(
            model_name='office',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='services.Office'),
        ),
        migrations.DeleteModel(
            name='Geha',
        ),
    ]
