# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-09-02 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20190901_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservice',
            name='canBeOrdered',
            field=models.BooleanField(default=False),
        ),
    ]
