# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-12-03 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20191007_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAddon',
            fields=[
                ('addon_id', models.AutoField(primary_key=True, serialize=False)),
                ('addon_name', models.CharField(max_length=50)),
                ('is_rquired', models.BooleanField(default=True)),
                ('file', models.ImageField(upload_to=services.models.upload_Addon_Image)),
                ('srv_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
            ],
        ),
    ]
