# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-09-03 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_subservice_canbeordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subserviceparameter',
            name='paramType',
            field=models.CharField(choices=[('أسم مالك الورقة المطلوبة', 'أسم مالك الورقة المطلوبة'), ('الرقم القومى الخاص بطالب الأوراق', 'الرقم القومى الخاص بطالب الأوراق')], default='أسم مالك الورقة المطلوبة', max_length=40),
        ),
    ]
