# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-12-08 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20191207_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceaddonanswer',
            name='ord_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Order'),
        ),
    ]
