# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-09-03 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20190903_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subserviceparameter',
            name='paramName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subserviceparameter',
            name='paramType',
            field=models.CharField(choices=[('Text', 'Text'), ('Number', 'Number'), ('Date', 'Date'), ('City List', 'City List')], default='Text', max_length=40),
        ),
    ]
