# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-09-03 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20190903_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='subserviceparameter',
            name='iconName',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
