# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-09-04 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_order_requiredfieldsanswers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='papers',
            field=models.TextField(blank=True, default=''),
        ),
    ]
