# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-09-04 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20190904_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='requiredFieldsAnswers',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='actions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='subserviceparameter',
            name='conditions',
            field=models.TextField(blank=True),
        ),
    ]
